Export Fix
Open-Sn/opensn pull request #142
Opened 2024-02-19 18:17 UTC by rodriguez-jay

2024-02-19 18:21 UTC, andrsd commented
I am going to re-open this. This is correct. I will just edit the PR description...

2024-02-19 18:22 UTC, andrsd requested changes

2024-02-19 18:22 UTC, andrsd commented on lua/framework/mesh/export/lua_mesh_export.cc
> +
Remove this line and your PR is good to go in as far as I can tell.

2024-02-19 20:40 UTC, ragusa approved these changes
do the change requested by David. I am going to approve as his request will still block this PR until resolved.

2024-02-19 22:44 UTC, closed without merging

2024-02-19 22:54 UTC, rodriguez-jay commented
Should be good to go

2024-02-20 12:48 UTC, andrsd commented
I don't understand what is going on here. I asked you to fix your patch. You closed the PR, deleted your feature branach and said this is good to go in? 😕

2024-02-20 13:41 UTC, rodriguez-jay commented
I thought I closed the PR on my personal fork. After merging my branch into main. Did I accident close the PR here?

2024-02-20 13:52 UTC, andrsd commented
Well, the issue number is #132. 142 was the PR number. IDK what you did in your personal fork, but it hosed up this PR.

However, I salvaged and fixed your code in PR #145 . You will get credit for the code change, the patch has you as an author...

2024-02-20 14:16 UTC, rodriguez-jay commented
Thanks for the help David. Sorry for wrinkling things up there.