Adding install target
Open-Sn/opensn pull request #177
Opened 2024-03-13 15:32 UTC by zhardy-lanl

Implements `make install` to allow for use by external applications.

2024-03-13 15:47 UTC, andrsd requested changes

2024-03-13 15:47 UTC, andrsd commented on CMakeLists.txt
> +            FILES_MATCHING PATTERN "*.h"
This has too much indentation. Should be indented by 8 spaces (i.e. 2 x 4 spaces) like the `install` command above.

2024-03-13 15:56 UTC, andrsd approved these changes

2024-03-13 16:37 UTC, ragusa approved these changes

2024-03-14 05:16 UTC, wdhawkins approved these changes

2024-03-14 14:35 UTC, merged