Initial commit of tools directory
Open-Sn/opensn pull request #232
Opened 2024-04-27 04:16 UTC by wdhawkins

Adding `tools` directory.  This initial commit includes:

`developer/lsan.supp`: lsan suppressions file
`xs/OpenMC_Create_MGXS_Library.ipynb`: Jupyter notebook for creating OpenMC cross-section libraries

2024-04-28 00:03 UTC, ragusa commented
should we have a readme in the tools directory explaining what is found in its subdirectory? or a readme pointing to readme's in each subdirectory and those readme should each have one bullet describing their use/purpose?

2024-04-29 14:00 UTC, zhardy-lanl approved these changes

2024-04-29 14:00 UTC, zhardy-lanl commented on tools/xs/OpenMC_Create_MGXS_Library.ipynb
My only comment here would be to ask whether we want to stick to file naming conventions here or not. I would suggest modifying the name to `create_openmc_xslib.ipynb` (even if sticking to caps).

2024-04-29 14:02 UTC, andrsd commented on tools/xs/OpenMC_Create_MGXS_Library.ipynb
I think we should stick to the naming conventions, i.e. `create_openmc_xslib.ipynb`

2024-04-29 14:16 UTC, wdhawkins commented on tools/xs/OpenMC_Create_MGXS_Library.ipynb
Fixed.

2024-04-29 14:24 UTC, andrsd approved these changes

2024-04-30 18:09 UTC, ragusa approved these changes
can you change the readme.txt to a markdown readme? if not, i'll do it soon

2024-04-30 18:09 UTC, ragusa commented on tools/README.txt
> +This directory contains various tools for use by both devleopers and users.
typo

2024-05-01 15:02 UTC, ragusa requested changes
please address comments

2024-05-03 01:34 UTC, wdhawkins commented on tools/README.txt
> +This directory contains various tools for use by both devleopers and users.
Fixed.

2024-05-03 02:50 UTC, ragusa approved these changes

2024-05-03 04:28 UTC, merged