Changing boundary ID to boundary name mapping in orthogonal mesh generator
Open-Sn/opensn pull request #255
Opened 2024-05-07 19:42 UTC by andrsd

Closes #229

2024-05-07 20:39 UTC, zhardy-lanl requested changes
If we are switching XMAX=0 -> XMIN=0, then the boundary IDs assigned to each boundary should change. It seems that the changes here simply calls XMAX XMIN when it is still XMAX in reality. For example, see [this](https://github.com/Open-Sn/opensn/pull/255/files#diff-eea216c0d703c277f363af126cfc51ad97540fdd1135309bac14922cd57036c8R266-R268).

It took me a few minutes to understand why the regressions tests are passing, and I think I know why now. In `LBSSolver`, the same ordering still exists, and since the indices did not change, there is no underlying difference. See [this](https://github.com/Open-Sn/opensn/blob/main/modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc#L36).

2024-05-07 20:39 UTC, zhardy-lanl commented on framework/mesh/mesh_generator/orthogonal_mesh_generator.cc
> +          face.neighbor = cmap[i - 1][j]; /*YMAX*/
These are interesting comments, aren't these interior cells here? I wonder why these comments were there in the first place... Either way, they should be reverted. The change in boundary ordering doesn't change the orientation of the cell during construction, especially not interior cells.

2024-05-07 20:39 UTC, zhardy-lanl commented on framework/mesh/mesh_generator/orthogonal_mesh_generator.cc
> +          face.neighbor = XMIN;
This doesn't seem right. The boundary is still `XMAX`. The thing that changed is the index of `XMAX`, not the boundary that this is.

2024-05-07 20:39 UTC, zhardy-lanl commented on framework/mesh/mesh_generator/orthogonal_mesh_generator.cc
> +          face.neighbor = XMAX;
See other comment.

2024-05-07 20:39 UTC, zhardy-lanl commented on framework/mesh/mesh_generator/orthogonal_mesh_generator.cc
> +          face.neighbor = YMIN;
See other comment.

2024-05-07 20:39 UTC, zhardy-lanl commented on framework/mesh/mesh_generator/orthogonal_mesh_generator.cc
> +          face.neighbor = YMAX;
See other comment.

2024-05-07 20:39 UTC, zhardy-lanl commented on framework/mesh/mesh_generator/orthogonal_mesh_generator.cc
> +          face.neighbor = (j == max_j) ? XMIN : cmap[i][j + 1][k];
See other comment.

2024-05-07 20:39 UTC, zhardy-lanl commented on framework/mesh/mesh_generator/orthogonal_mesh_generator.cc
> +          face.neighbor = (j == 0) ? XMAX : cmap[i][j - 1][k];
See other comment.

2024-05-07 20:39 UTC, zhardy-lanl commented on framework/mesh/mesh_generator/orthogonal_mesh_generator.cc
> +          face.neighbor = (i == max_i) ? YMIN : cmap[i + 1][j][k];
See other comment.

2024-05-07 20:39 UTC, zhardy-lanl commented on framework/mesh/mesh_generator/orthogonal_mesh_generator.cc
> +          face.neighbor = (i == 0) ? YMAX : cmap[i - 1][j][k];
See other comment.

2024-05-07 20:39 UTC, zhardy-lanl commented on framework/mesh/mesh_generator/orthogonal_mesh_generator.cc
> +          face.neighbor = (k == 0) ? ZMAX : cmap[i][j][k - 1];
See other comment.

2024-05-13 20:45 UTC, zhardy-lanl approved these changes

2024-05-14 02:37 UTC, ragusa approved these changes

2024-05-14 20:36 UTC, wdhawkins approved these changes

2024-05-15 00:54 UTC, merged