Fixing a minor memory issue in the discrete ordinates solver destructor
Open-Sn/opensn pull request #271
Opened 2024-05-16 21:30 UTC by wdhawkins

Debugging this issue led to some minor cleanup in lbs_groupset. One problem being that not all of the lbs_groupset member variables were properly initialized. It also lead to a small fix in runtime::Finalize().

2024-05-16 22:15 UTC, ragusa approved these changes

2024-05-17 01:44 UTC, andrsd requested changes

2024-05-17 01:44 UTC, andrsd commented on modules/linear_boltzmann_solvers/lbs_solver/groupset/lbs_groupset.h
> +  void init(int id);
`init` -> `Init`

2024-05-17 16:06 UTC, wdhawkins commented on modules/linear_boltzmann_solvers/lbs_solver/groupset/lbs_groupset.h
> +  void init(int id);
Fixed. Thanks!

2024-05-21 13:56 UTC, andrsd approved these changes

2024-05-21 17:44 UTC, zhardy-lanl requested changes
Please remove the blank lines from the `GetInputParameters` routine for groupsets except to break logically related groups.

2024-05-21 17:44 UTC, zhardy-lanl commented on modules/linear_boltzmann_solvers/lbs_solver/groupset/lbs_groupset.cc
>                                     " e.g. A 4 group problem <TT>groups_from_to= {0, 3}</TT>");
```suggestion
                                   "The first and last group id this groupset operates on, "
                                   " e.g. <TT>groups_from_to= {0, 3}</TT> for a 4 group problem.");
```

2024-05-21 19:11 UTC, wdhawkins commented on modules/linear_boltzmann_solvers/lbs_solver/groupset/lbs_groupset.cc
>                                     " e.g. A 4 group problem <TT>groups_from_to= {0, 3}</TT>");
Fixed.

2024-05-21 21:48 UTC, zhardy-lanl approved these changes

2024-05-22 01:30 UTC, merged