Theory manual and some doco clean up
Open-Sn/opensn pull request #294
Opened 2024-06-13 17:43 UTC by ragusa

The theory manual has been ported from latex. The process is 95% automatic but the figures had to be fixed by hand. 

Some additional cleanup to the doco was made while adding the theory manual

2024-06-17 15:33 UTC, andrsd commented
Add this patch, so that the github action can generate the doco:

```
diff --git a/doc/requirements.txt b/doc/requirements.txt
index 48ae5445..94971b73 100644
--- a/doc/requirements.txt
+++ b/doc/requirements.txt
@@ -3,3 +3,4 @@ myst-parser
 sphinx
 sphinx-design
 sphinx-rtd-theme
+sphinxcontrib-bibtex
```

2024-06-17 16:05 UTC, andrsd requested changes

2024-06-17 16:05 UTC, andrsd commented on doc/theory/parallelization.rst
> +given direction-by -direction. At the level of a given group :math:`g`,
Extra space in "direction-by -direction"

2024-06-17 16:05 UTC, andrsd commented on doc/theory/parallelization.rst
> +for a given direction :math:`d`, a full- domain transport sweep is
Extra space in "full- domain"

2024-06-18 01:11 UTC, ragusa commented on doc/theory/discretization.rst
> +Angle Discretization (the :math:`S_n` method)
I have simplified the title to just have Sn in plain text then.

2024-06-18 01:15 UTC, ragusa commented on doc/CMakeLists.txt
> +    configure_file(${CMAKE_SOURCE_DIR}/tutorials/index.rst src/tutorials/index.rst)
I actually add forgotten to add that new index file that is located in the `tutorials` folder. good catch

2024-06-18 01:15 UTC, ragusa commented
comments resolved. requirements.txt updated. thanks

2024-06-18 03:07 UTC, andrsd approved these changes

2024-06-18 17:23 UTC, ragusa commented
@zhardy-lanl @wdarylhawkins : reviewing doco is not necessarily easy as it's a bunch of rst text. But you can always checkout my branch, go to the `build/` folder, configure, and then `make doc`. If, in the past, you built the doco locally, you likely have most of the python requirements satisfied but you will need to pip install the latest addition to the requirements, sphinxcontrib-bibtex.

2024-06-20 14:38 UTC, zhardy-lanl approved these changes

2024-06-20 15:18 UTC, wdhawkins approved these changes

2024-06-20 15:42 UTC, merged