Physics Reorganization
Open-Sn/opensn pull request #389
Opened 2024-10-17 14:42 UTC by zhardy-lanl

- Moved `solver.h(cc)` to `physics` directory and removed `physics/solver_base`.
- Moved `basic_options.h(cc)` to `data_types` and removed `physics/basic_options`.

2024-10-17 15:25 UTC, ragusa approved these changes

2024-10-17 16:30 UTC, andrsd requested changes

2024-10-17 16:30 UTC, andrsd commented on framework/data_types/basic_options.cc
> +#include "basic_options.h"
"framework/data_types/basic_options.h"

2024-10-17 16:35 UTC, zhardy-lanl commented on framework/data_types/basic_options.cc
> +#include "basic_options.h"
Done.

2024-10-17 16:36 UTC, andrsd approved these changes

2024-10-17 16:40 UTC, andrsd commented
There was some strange error in the SPDX checker. I re-ran the workflow and it is ok now. Just FYI...

2024-10-28 21:40 UTC, wdhawkins approved these changes

2024-10-31 14:33 UTC, merged