Creeatibg LBSSolverVecOps class for group-scoped vector operations
Open-Sn/opensn pull request #425
Opened 2024-11-24 06:29 UTC by wdhawkins

This PR moves group-scoped vector operations out of LBSSolver and DiscreteOrdinatesSolver and into a standalone LBSSolverVecOps class.  It consolidates the base and derived vector ops methods into a single helper class.

I'm hoping this PR will generate some discussion on the future of LBSSolver. If we want LBSSolver to be a fancy container class that encapsulates problem parameters and solution data - with most of the heavy lifting delegated to helper classes -this PR fits in with that vision. Along those lines, I could see us splitting out other functionality like fission ops, etc. into helper classes.

If we want to retain the existing LBSSolver structure, I can easily replace the base and derived vector ops methods with the new, refactored versions.

2024-11-25 17:46 UTC, andrsd commented
The original code had polymorphism on these methods, so the behavior of LSBSolver and DiscreteOrdinatesSolver was different. In some methods, the pure LBS ignored the `DelayedPsi` while the DO used them. I guess the MG diffusion solver does not call these, so all works as expected?

2024-11-25 18:34 UTC, andrsd approved these changes

2024-11-27 19:05 UTC, zhardy-lanl requested changes

2024-11-27 19:05 UTC, zhardy-lanl commented on modules/linear_boltzmann_solvers/lbs_solver/vecops/lbs_solver_vecops.h
> +class LBSSolverVecOps
```suggestion
class LBSVecOps
```
Just a suggestion

2024-11-27 19:05 UTC, zhardy-lanl commented on modules/linear_boltzmann_solvers/lbs_solver/vecops/lbs_solver_vecops.h
I would not make a subdirectory for a single `.[h|cc]` file. Eventually we can maybe have a `helpers` directory that houses these types of things, but for now I don't think this is necessary.

2024-11-27 20:56 UTC, wdhawkins commented on modules/linear_boltzmann_solvers/lbs_solver/vecops/lbs_solver_vecops.h
> +class LBSSolverVecOps
Fixed.

2024-11-27 20:57 UTC, wdhawkins commented on modules/linear_boltzmann_solvers/lbs_solver/vecops/lbs_solver_vecops.h
Fixed.

2024-11-27 20:58 UTC, zhardy-lanl approved these changes

2024-11-27 22:17 UTC, ragusa approved these changes

2024-11-27 23:16 UTC, merged