Add `MeshMapping` for future separate mesh acceleration
Open-Sn/opensn pull request #457
Opened 2024-12-22 01:13 UTC by loganharbour

Adds the start for mapping between a fine and a coarse mesh for acceleration. I'm attempting to do this in pieces instead of one big PR, testing pieces at a time.

- Still serial only. Eventually, the fine mesh will be allowed to be parallel. The coarse mesh will remain serial (still need a way to do this).
- The execution of this isn't what it will be when actually used in production. Waiting on https://github.com/Open-Sn/opensn/pull/435 to be able to input multiple mesh generators. Another object will instantiate and execute this in the future. 
- The naming might be awful. `MeshMapping` might be confusing when compared with the discretization and `GetCellMapping`.

Adding comments for parts I have questions on / want specific feedback on.

2024-12-22 01:14 UTC, loganharbour commented on framework/mesh/mesh_continuum/mesh_continuum.cc
> +  // Check each face. A point inside the face will give a negative value, a point on the face
This is a significant change. If the polyhedra are convex (they should be, yeah?), this is valid.

2024-12-22 01:14 UTC, loganharbour commented on framework/mesh/mesh_continuum/mesh_continuum.cc
> +  // 1D, face is a point; simple equality check (could we just check z here?)
In the case where we have a point face, is it guaranteed to be a slab? Can I just check the z dimension here?

2024-12-22 01:15 UTC, loganharbour commented on lua/framework/mesh/mesh_mapping/mesh_mapping_build.cc
> +}
Again... this is only temporary. But it makes life a bit easier to review these contributions in small pieces, while still testing them.

2025-01-18 23:49 UTC, loganharbour commented
Requires https://github.com/Open-Sn/opensn/pull/464 and https://github.com/Open-Sn/opensn/pull/456.

2025-01-20 14:22 UTC, loganharbour commented
@wdarylhawkins another action trigger please when possible

2025-02-13 13:57 UTC, andrsd commented on framework/mesh/mesh_mapping/mesh_mapping.cc
> +  // Instantiate the maps; *Mapping constructor takes the cell to size the face maps.
Is the star (`*`) in front of "Mapping" a typo?

2025-02-13 14:02 UTC, andrsd requested changes

2025-02-13 14:02 UTC, andrsd commented on framework/mesh/mesh_mapping/mesh_mapping.h
> +  /// Mappign for fine cells to a coarse cell.
"Mappign" -> "Mapping"

2025-02-13 14:03 UTC, ragusa approved these changes

2025-02-14 04:11 UTC, loganharbour commented on framework/mesh/mesh_mapping/mesh_mapping.cc
> +  // Instantiate the maps; *Mapping constructor takes the cell to size the face maps.
Nope. Supposed to lazily represent [Coarse,Fine]Mapping

2025-02-14 04:16 UTC, loganharbour commented on framework/mesh/mesh_continuum/mesh_continuum.cc
> +    if (!InsideEdge(i, i + 1))
I tried this, didn't think about it much, and then tests failed. And I didn't have the energy on the couch to understand why it didn't work

2025-02-14 11:48 UTC, andrsd commented on framework/mesh/mesh_continuum/mesh_continuum.cc
> +    if (!InsideEdge(i, i + 1))
Ok.

2025-02-14 11:54 UTC, andrsd approved these changes

2025-02-14 11:56 UTC, andrsd commented on framework/mesh/mesh_mapping/mesh_mapping.cc
> +  // Instantiate the maps; *Mapping constructor takes the cell to size the face maps.
Fairly common syntax to use for such a case is  also `{Coarse|Fine}Mapping`. But your edit is good too...

2025-02-14 14:56 UTC, merged