update to logo/banner, readme, and MacOS install instructions
Open-Sn/opensn pull request #82
Opened 2024-01-20 20:57 UTC by ragusa

update to logo/banner, readme, and small update to MacOS install instructions

2024-01-20 21:14 UTC, andrsd requested changes

2024-01-20 21:14 UTC, andrsd commented on doc/install_linux_easy.md
> +**Important:**  If you want to contribute to **OpenSn**, it is strongly recommended to first fork the **Chi-Tech** repository into your own Git account and then to clone your fork.
There is one more ChiTech reference in this sentence.

2024-01-20 21:14 UTC, andrsd commented on doc/install_linux_easy.md
> +Clone the **OpenSn** repository.  Go the folder where you want to keep Chi-Tech relevant stuff:
One more Chi-Tech reference here as well.

2024-01-20 21:14 UTC, andrsd commented on doc/install_linux_easy.md
> +    $ git clone https://github.com/Open-Sn/opensn.git /path/to/opensn
The previous sentence said "Go to folder", so no need to specify the path. But, may be even better is to provide the instructions like this:
```
$ cd /some/path/
$ git clone ...
```

2024-01-20 23:08 UTC, andrsd approved these changes

2024-01-21 05:17 UTC, wdhawkins approved these changes

2024-01-21 15:10 UTC, merged